-- Table: users

-- DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    first_name character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    last_name character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    gender character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    password character varying(255) COLLATE pg_catalog."default" NOT NULL,
    role character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    avatar character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    plant character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    sap_id character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    integration_id character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    other_info character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    branch character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    is_block integer NOT NULL DEFAULT 0,
    email_verified_at timestamp without time zone,
    remember_token character varying(100) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    created_at timestamp without time zone,
    updated_at timestamp without time zone,
    imagesign character varying(255) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    username character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_username_key UNIQUE (username)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS users
    OWNER to postgres;